main:
	g++ main.cpp -lgum -lGL -lglfw -lGLEW -lm -lfreetype -o gum_test

phys:
	g++ phys.cpp -lgum -lGL -lglfw -lGLEW -lm -lfreetype -o phys_test

font:
	g++ font.cpp -lgum -lGL -lglfw -lGLEW -lm -lfreetype -o font_test
