main:
	g++ main.cpp -lgum -lGL -lglfw -lGLEW -lm -lfreetype -I/usr/include/freetype2 -o gum_test

phys:
	g++ phys.cpp -lgum -lGL -lglfw -lGLEW -lm -lfreetype -I/usr/include/freetype2 -o phys_test

font:
	g++ font.cpp -lgum -lGL -lglfw -lGLEW -lm -lfreetype -I/usr/include/freetype2 -o font_test
